In [1]:
import pandas as pd
import json

with open('conso.json', 'r') as json_file:
    data = json.load(json_file)

df = pd.DataFrame(data)
df.head()

,date_heure,date,heure,consommation_brute_gaz_grtgaz,statut_grtgaz,consommation_brute_gaz_terega,statut_terega,consommation_brute_gaz_totale,consommation_brute_electricite_rte,statut_rte,consommation_brute_totale
0,2023-06-30T23:30:00+02:00,30/06/2023,23:30,NaN,None,NaN,None,NaN,41970,Consolidé,NaN
1,2023-06-30T23:00:00+02:00,30/06/2023,23:00,21296.0,Meilleur Statut,1112.0,Définitif,22408.0,42846,Consolidé,65254.0
2,2023-06-30T22:30:00+02:00,30/06/2023,22:30,NaN,None,NaN,None,NaN,43682,Consolidé,NaN
3,2023-06-30T22:00:00+02:00,30/06/2023,22:00,23157.0,Meilleur Statut,1164.0,Définitif,24321.0,42536,Consolidé,66857.0
4,2023-06-30T21:30:00+02:00,30/06/2023,21:30,NaN,None,NaN,None,NaN,41130,Consolidé,NaN